name: deploy to raspberry pi

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Update and reload bot
        run: |
          cd
          cd dev/rambot
          git pull origin main
          npm install
          pm2 reload index.js
