name: test raspberry pi

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
        run: |
          cd rambot
          cat index.js
