name: deploy to raspberry pi

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull changes from github
        run: |
          cd dev/rambot
          git pull origin main

      - name: Install Dependencies
        run: npm install

      - name: Reload the bot
        run: pm2 reload index.js
